# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  # the root website directory
  command = "npm run build"
  # the build command
  functions = "func/"
  
[[redirects]]
  from = "/api/ron/*"
  to = "https://ron-swanson-quotes.herokuapp.com/v2/:splat"
  status = 200
  
[[redirects]]
  from = "/api/yes"
  to = "/.netlify/functions/yep"
  status = 200

[[redirects]]
  from = "/api/octo"
  to = "/.netlify/functions/octo"
  status = 200